/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.magacin;

import controller.ClientController;
import domain.Magacin;
import domain.Namena;
import domain.Radnik;
import forme.trebovanje.FormUnosTrebovanja;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




public class FormUnosMagacina extends javax.swing.JDialog {

    /**
     * Creates new form FormUnosMagacina
     */
    public FormUnosMagacina(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos magacina");
        popuniRadnike();
        popuniNamenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JFormattedTextField();
        txtNaziv = new javax.swing.JTextField();
        cmbRadnik = new javax.swing.JComboBox();
        cmbNamena = new javax.swing.JComboBox();
        btnUnesi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra magacina:");

        jLabel2.setText("Naziv magacina:");

        jLabel3.setText("Racunopolagac:");

        jLabel4.setText("Namena:");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        cmbRadnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbNamena.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUnesi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnesi.setText("Unesi magacin");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSifra)
                            .addComponent(txtNaziv)
                            .addComponent(cmbRadnik, 0, 142, Short.MAX_VALUE)
                            .addComponent(cmbNamena, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbNamena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnUnesi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            if(txtSifra.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti sifru magacina!");
                return;
            }
            if(txtNaziv.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti naziv magacina!");
                return;
            }
            Long sifMagacina = Long.parseLong(txtSifra.getText());
            String nazivMagacina = txtNaziv.getText();
            Radnik r = (Radnik)cmbRadnik.getSelectedItem();
            String namena = String.valueOf((Namena)cmbNamena.getSelectedItem());
            Date poslDatumTreb = null;
            
            Magacin m = new Magacin(sifMagacina, nazivMagacina, r, namena, poslDatumTreb);
            
            ClientController.getInstance().addMagacin(m);
            FormListaMagacina lm = (FormListaMagacina) getParent();
            lm.refreshTable();
            JOptionPane.showMessageDialog(this, "Uspesno unet magacin.");
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(FormUnosMagacina.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_btnUnesiActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesi;
    private javax.swing.JComboBox cmbNamena;
    private javax.swing.JComboBox cmbRadnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JFormattedTextField txtSifra;
    // End of variables declaration//GEN-END:variables
    
    
    private void popuniRadnike() {
        try {
            ArrayList<Radnik> radnici;
            
            radnici = ClientController.getInstance().getAllRadnik();
            cmbRadnik.removeAllItems();
            
            for(Radnik r: radnici){
                cmbRadnik.addItem(r);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosMagacina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniNamenu() {
        try {
            ArrayList<Namena> namene;
            
            namene = ClientController.getInstance().getAllNamena();
            cmbNamena.removeAllItems();
            
            for(Namena n: namene){
                cmbNamena.addItem(n);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosMagacina.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
   

}
