/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.magacin;

import controller.ClientController;
import domain.Magacin;
import domain.Namena;
import domain.Radnik;
import forme.trebovanje.FormUnosTrebovanja;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


public class FormIzmenaMagacina extends javax.swing.JDialog {


    private Magacin m;
    private Date datumPre;
    FormListaMagacina lm = (FormListaMagacina) getParent();
    public FormIzmenaMagacina(JDialog parent, boolean modal, Magacin m) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("izmena magacina");
        this.m = m;
        txtSifra.setEnabled(false);
        popuniRadnike();
        popuniNamenu();
        datumPre = m.getPoslDatumTreb();
        txtSifra.setText(String.valueOf(m.getSifMagacina()));
        txtNaziv.setText(m.getNazivMagacina());
        cmbRadnik.getModel().setSelectedItem(m.getRadnik());
        cmbNamena.getModel().setSelectedItem(m.getNamena());
        txtDatum.setDate(m.getPoslDatumTreb());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JFormattedTextField();
        txtNaziv = new javax.swing.JTextField();
        cmbRadnik = new javax.swing.JComboBox();
        cmbNamena = new javax.swing.JComboBox();
        btnIzmeni = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDatum = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra magacina:");

        jLabel2.setText("Naziv magacina:");

        jLabel3.setText("Racunopolagac:");

        jLabel4.setText("Namena:");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        cmbRadnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbNamena.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmeni.setText("Izmeni magacin");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel5.setText("Poslednji datum treb:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNamena, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbNamena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            
            if(txtNaziv.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti naziv magacina!");
                return;
            }
            
            m.setNazivMagacina(txtNaziv.getText());
            m.setRadnik((Radnik)cmbRadnik.getSelectedItem());
            m.setNamena(String.valueOf(cmbNamena.getSelectedItem()));
            
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            String datumNovi = null;
            String datumStari = null;
            if(txtDatum.getDate()!=null){
                datumNovi = dateFormat.format(txtDatum.getDate());
            }
            if(datumPre!= null){
                datumStari = dateFormat.format(datumPre);
            }
            
            if (datumStari == null && datumNovi == null) {
                m.setPok(0);
            }else if(datumStari == null && datumNovi!=null || datumStari != null && datumNovi==null || !datumStari.equals(datumNovi)){
                m.setPok(1);
                m.setFormatDate(datumNovi);
            } else{
                m.setPok(0);
            }
            
            ClientController.getInstance().updateMagacin(m);
            JOptionPane.showMessageDialog(this, "Uspesno izmenjen magacin.");
            lm.refreshTable();
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            lm.refreshTable();
            this.dispose();
        }
        
                
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbNamena;
    private javax.swing.JComboBox cmbRadnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JFormattedTextField txtSifra;
    // End of variables declaration//GEN-END:variables
    
    
    private void popuniRadnike() {
        try {
            ArrayList<Radnik> radnici;
            
            radnici = ClientController.getInstance().getAllRadnik();
            cmbRadnik.removeAllItems();
            
            for(Radnik r: radnici){
                cmbRadnik.addItem(r);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormIzmenaMagacina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniNamenu() {
        try {
            ArrayList<Namena> namene;
            
            namene = ClientController.getInstance().getAllNamena();
            cmbNamena.removeAllItems();
            
            for(Namena n: namene){
                cmbNamena.addItem(n);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormIzmenaMagacina.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
   

}
