/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.proizvod.FormListaProizvoda;
import controller.ClientController;
import domain.JedinicaMere;
import forme.PoslovniPartnerView.FormListaPoslovnihPartnera;
import forme.ZapisnikOPrijemuMaterijala.FormListaZOPM;
import forme.istorijaStanjaZaliha.FormListaIstorijeStanjaZaliha;
import forme.magacin.FormListaMagacina;
import forme.pakovanje.FormListaPakovanja;
import forme.radnik.FormListaRadnika;
import forme.stavkaZapisnikaOPrijemuMaterijala.FormListaStavkiZOPM;
import forme.trebovanje.FormListaTrebovanja;
import forme.zapisnikOUlazuGotoveRobe.FormListaZapisnikaGR;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;


public class FormMain extends javax.swing.JDialog {

    ImageIcon image = new ImageIcon("OracleJava.jpg");

    public FormMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Aplikacija");
        lblSlika.setText("");
        lblSlika.setIcon(image);
      
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        lblSlika = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        itemProizvod = new javax.swing.JMenuItem();
        itemIstorija = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        itemProizvod1 = new javax.swing.JMenuItem();
        itemZOPM = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        itemRadnik = new javax.swing.JMenuItem();
        itemPakovanje = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        itemZGR = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        itemPoslovniPartner = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        itemProizvod2 = new javax.swing.JMenuItem();
        itemIstorija1 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        itemTrebovanje = new javax.swing.JMenuItem();
        itemMagacin = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenuItem3.setText("jMenuItem3");

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar5.add(jMenu11);

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSlika.setText("lab");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Baze podataka 3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Implementacija sistema");

        jMenuBar1.setForeground(new java.awt.Color(1, 1, 1));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu6.setText("2 NF");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemProizvod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/proizvod.png"))); // NOI18N
        itemProizvod.setText("Proizvod");
        itemProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProizvodActionPerformed(evt);
            }
        });
        jMenu6.add(itemProizvod);

        itemIstorija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/istorija.png"))); // NOI18N
        itemIstorija.setText("Istorija stanja zaliha");
        itemIstorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIstorijaActionPerformed(evt);
            }
        });
        jMenu6.add(itemIstorija);

        jMenuBar1.add(jMenu6);

        jMenu12.setText("3 NF");
        jMenu12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemProizvod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/proizvod.png"))); // NOI18N
        itemProizvod1.setText("Proizvod");
        itemProizvod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProizvod1ActionPerformed(evt);
            }
        });
        jMenu12.add(itemProizvod1);

        itemZOPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zopm.png"))); // NOI18N
        itemZOPM.setText("Zapisnik o prijemu materijala");
        itemZOPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemZOPMActionPerformed(evt);
            }
        });
        jMenu12.add(itemZOPM);

        jMenuBar1.add(jMenu12);

        jMenu13.setText("Korisnicki tipovi");
        jMenu13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemRadnik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/radnik.png"))); // NOI18N
        itemRadnik.setText("Radnik");
        itemRadnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRadnikActionPerformed(evt);
            }
        });
        jMenu13.add(itemRadnik);

        itemPakovanje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pakovanje.png"))); // NOI18N
        itemPakovanje.setText("Pakovanje");
        itemPakovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPakovanjeActionPerformed(evt);
            }
        });
        jMenu13.add(itemPakovanje);

        jMenuBar1.add(jMenu13);

        jMenu14.setText("Horizontalno particionisanje");
        jMenu14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemZGR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zgr.png"))); // NOI18N
        itemZGR.setText("ZapisnikOUlazuGotoveRobe");
        itemZGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemZGRActionPerformed(evt);
            }
        });
        jMenu14.add(itemZGR);

        jMenuBar1.add(jMenu14);

        jMenu15.setText("Vertikalno particionisanje");
        jMenu15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemPoslovniPartner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/partner.png"))); // NOI18N
        itemPoslovniPartner.setText("PoslovniPartner");
        itemPoslovniPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPoslovniPartnerActionPerformed(evt);
            }
        });
        jMenu15.add(itemPoslovniPartner);

        jMenuBar1.add(jMenu15);

        jMenu16.setText("Oprimizacija baze 1");
        jMenu16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemProizvod2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/proizvod.png"))); // NOI18N
        itemProizvod2.setText("Proizvod");
        itemProizvod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProizvod2ActionPerformed(evt);
            }
        });
        jMenu16.add(itemProizvod2);

        itemIstorija1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/istorija.png"))); // NOI18N
        itemIstorija1.setText("Istorija stanja zaliha");
        itemIstorija1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIstorija1ActionPerformed(evt);
            }
        });
        jMenu16.add(itemIstorija1);

        jMenuBar1.add(jMenu16);

        jMenu17.setText("Oprimizacija baze 2");
        jMenu17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        itemTrebovanje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trebovanje.png"))); // NOI18N
        itemTrebovanje.setText("Trebovanje");
        itemTrebovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTrebovanjeActionPerformed(evt);
            }
        });
        jMenu17.add(itemTrebovanje);

        itemMagacin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magacin.png"))); // NOI18N
        itemMagacin.setText("Magacin");
        itemMagacin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMagacinActionPerformed(evt);
            }
        });
        jMenu17.add(itemMagacin);

        jMenuBar1.add(jMenu17);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE)
                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProizvodActionPerformed
        new FormListaProizvoda(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemProizvodActionPerformed

    private void itemIstorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIstorijaActionPerformed
        new FormListaIstorijeStanjaZaliha(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemIstorijaActionPerformed

    private void itemProizvod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProizvod1ActionPerformed
        new FormListaProizvoda(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemProizvod1ActionPerformed

    private void itemZOPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemZOPMActionPerformed
        new FormListaZOPM(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemZOPMActionPerformed

    private void itemRadnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRadnikActionPerformed
        new FormListaRadnika(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemRadnikActionPerformed

    private void itemPakovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPakovanjeActionPerformed
        new FormListaPakovanja(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemPakovanjeActionPerformed

    private void itemZGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemZGRActionPerformed
        new FormListaZapisnikaGR(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemZGRActionPerformed

    private void itemPoslovniPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPoslovniPartnerActionPerformed
         new FormListaPoslovnihPartnera(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemPoslovniPartnerActionPerformed

    private void itemProizvod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProizvod2ActionPerformed
        new FormListaProizvoda(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemProizvod2ActionPerformed

    private void itemIstorija1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIstorija1ActionPerformed
        new FormListaIstorijeStanjaZaliha(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemIstorija1ActionPerformed

    private void itemTrebovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTrebovanjeActionPerformed
        new FormListaTrebovanja(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemTrebovanjeActionPerformed

    private void itemMagacinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMagacinActionPerformed
        new FormListaMagacina(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemMagacinActionPerformed

        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListaProizvoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMain dialog = new FormMain(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemIstorija;
    private javax.swing.JMenuItem itemIstorija1;
    private javax.swing.JMenuItem itemMagacin;
    private javax.swing.JMenuItem itemPakovanje;
    private javax.swing.JMenuItem itemPoslovniPartner;
    private javax.swing.JMenuItem itemProizvod;
    private javax.swing.JMenuItem itemProizvod1;
    private javax.swing.JMenuItem itemProizvod2;
    private javax.swing.JMenuItem itemRadnik;
    private javax.swing.JMenuItem itemTrebovanje;
    private javax.swing.JMenuItem itemZGR;
    private javax.swing.JMenuItem itemZOPM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblSlika;
    // End of variables declaration//GEN-END:variables


}
