/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zapisnikOUlazuGotoveRobe;

import com.sun.istack.internal.logging.Logger;
import controller.ClientController;
import domain.Magacin;
import domain.OrganizacionaJedinica;
import domain.Radnik;
import domain.ZapisnikGRP;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




public class FormUnosZapisnikaGR extends javax.swing.JDialog {

    /**
     * Creates new form FormUnosZapisnikaGR
     */
    public FormUnosZapisnikaGR(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos zapisnika o ulazu gotove robe");
        popuniMagacine();
        popuniRadnike();
        popuniOrgJed();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JFormattedTextField();
        txtEvidencioni = new javax.swing.JFormattedTextField();
        txtDatum = new com.toedter.calendar.JDateChooser();
        txtOznaka = new javax.swing.JTextField();
        cmbOrgJed = new javax.swing.JComboBox();
        cmbRadnik = new javax.swing.JComboBox();
        cmbMagacin = new javax.swing.JComboBox();
        btnUnesi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra zapisnika:");

        jLabel2.setText("Evidencioni broj:");

        jLabel3.setText("Datum:");

        jLabel4.setText("Oznaka:");

        jLabel5.setText("Org. jed:");

        jLabel6.setText("Uneo:");

        jLabel7.setText("Magacin:");

        txtSifra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txtSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraActionPerformed(evt);
            }
        });

        txtEvidencioni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        txtDatum.setDateFormatString("dd.MM.yyyy.");

        txtOznaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOznakaActionPerformed(evt);
            }
        });

        cmbOrgJed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbRadnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRadnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRadnikActionPerformed(evt);
            }
        });

        cmbMagacin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUnesi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnesi.setText("Unesi zapisnik");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(cmbMagacin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEvidencioni)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSifra)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(txtOznaka))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbOrgJed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRadnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEvidencioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrgJed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnUnesi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRadnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRadnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRadnikActionPerformed

    private void txtSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            if(txtSifra.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti sifru zapisnika!");
                return;
            }
            if(txtEvidencioni.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti evidencioni broj!");
                return;
            }
            if(txtDatum.getDate() == null){
                JOptionPane.showMessageDialog(this, "Morate uneti datum dokumenta!");
                return;
            }
            Long sifZGR = Long.parseLong(txtSifra.getText());
            Long evidencioniBroj = Long.parseLong(txtEvidencioni.getText());
            Date datum = txtDatum.getDate();
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            String datum1 = dateFormat.format(datum);
            String oznaka = txtOznaka.getText();
            OrganizacionaJedinica org = (OrganizacionaJedinica)cmbOrgJed.getSelectedItem();
            Radnik r = (Radnik) cmbRadnik.getSelectedItem();
            Magacin m = (Magacin)cmbMagacin.getSelectedItem();
            
            ZapisnikGRP z = new ZapisnikGRP(sifZGR, evidencioniBroj, datum1, oznaka, org, r, m);
            
            ClientController.getInstance().addZapisnikGR(z);
            FormListaZapisnikaGR lz = (FormListaZapisnikaGR) getParent();
            lz.refreshTable();
            JOptionPane.showMessageDialog(this, "Uspesno unet zapisnik.");
            this.dispose();
        } catch (Exception ex) {
            //java.util.logging.Logger.getLogger(FormUnosZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void txtOznakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOznakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOznakaActionPerformed

    /**
     * @param args the command line arguments
     */

    private void popuniMagacine() {
        try {
            ArrayList<Magacin> magacini;
            
            magacini = ClientController.getInstance().getAllMagacin();
            cmbMagacin.removeAllItems();
            
            for(Magacin m: magacini){
                cmbMagacin.addItem(m);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesi;
    private javax.swing.JComboBox cmbMagacin;
    private javax.swing.JComboBox cmbOrgJed;
    private javax.swing.JComboBox cmbRadnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JFormattedTextField txtEvidencioni;
    private javax.swing.JTextField txtOznaka;
    private javax.swing.JFormattedTextField txtSifra;
    // End of variables declaration//GEN-END:variables

    private void popuniRadnike() {
        try {
            ArrayList<Radnik> radnici;
            
            radnici = ClientController.getInstance().getAllRadnik();
            cmbRadnik.removeAllItems();
            
            for(Radnik r: radnici){
                cmbRadnik.addItem(r);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniOrgJed() {
        try {
            ArrayList<OrganizacionaJedinica> jedinice;
            
            jedinice = ClientController.getInstance().getAllOrgJed();
            cmbOrgJed.removeAllItems();
            
            for(OrganizacionaJedinica j: jedinice){
                cmbOrgJed.addItem(j);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
