/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zapisnikOUlazuGotoveRobe;

import controller.ClientController;
import domain.Magacin;
import domain.OrganizacionaJedinica;
import domain.Radnik;
import domain.ZapisnikGRP;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




public class FormIzmenaZapisnikaGR extends javax.swing.JDialog {

    ZapisnikGRP z;
    public FormIzmenaZapisnikaGR(JDialog parent, boolean modal, ZapisnikGRP z) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Izmena zapisnika o ulazu gotove robe");
        this.z = z;
        popuniMagacine();
        popuniRadnike();
        popuniOrgJed();
        txtSifra.setText(String.valueOf(z.getSifZGR()));
        txtSifra.setEnabled(false);
        txtEvidencioni.setText(String.valueOf(z.getEvidencioniBroj()));
        txtDatum.setDate(z.getDatumDokumenta());
        txtOznaka.setText(z.getOznaka());
        cmbOrgJed.getModel().setSelectedItem(z.getOrgJed());
        cmbRadnik.getModel().setSelectedItem(z.getRadnik());
        cmbMagacin.getModel().setSelectedItem(z.getMagacin());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOznaka = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbOrgJed = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbRadnik = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbMagacin = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JFormattedTextField();
        txtEvidencioni = new javax.swing.JFormattedTextField();
        txtDatum = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra zapisnika:");

        cmbOrgJed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Evidencioni broj:");

        cmbRadnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRadnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRadnikActionPerformed(evt);
            }
        });

        jLabel3.setText("Datum:");

        cmbMagacin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Oznaka:");

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmeni.setText("Izmeni zapisnik");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel5.setText("Org. jed:");

        jLabel6.setText("Uneo:");

        jLabel7.setText("Magacin:");

        txtSifra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txtSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraActionPerformed(evt);
            }
        });

        txtEvidencioni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        txtDatum.setDateFormatString("dd.MM.yyyy.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEvidencioni, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbOrgJed, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEvidencioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbOrgJed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnIzmeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRadnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRadnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRadnikActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        try {
            if(txtEvidencioni.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti evidencioni broj!");
                return;
            }
            if(txtDatum.getDate() == null){
                JOptionPane.showMessageDialog(this, "Morate uneti datum dokumenta!");
                return;
            }
            
            z.setEvidencioniBroj(Long.parseLong(txtEvidencioni.getText()));
            z.setOznaka(txtOznaka.getText());
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            String datum = dateFormat.format(txtDatum.getDate());
            z.setDatumDokumenta(txtDatum.getDate());
            z.setFormatDate(datum);
            z.setOrgJed((OrganizacionaJedinica)cmbOrgJed.getSelectedItem());
            z.setRadnik((Radnik)cmbRadnik.getSelectedItem());
            z.setMagacin((Magacin)cmbMagacin.getSelectedItem());
            
            ClientController.getInstance().updateZapisnikGR(z);
            JOptionPane.showMessageDialog(this, "Uspesno izmenjen zapisnik.");
            FormListaZapisnikaGR lz = (FormListaZapisnikaGR) getParent();
            lz.refreshTable();        
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FormIzmenaZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void txtSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbMagacin;
    private javax.swing.JComboBox cmbOrgJed;
    private javax.swing.JComboBox cmbRadnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JFormattedTextField txtEvidencioni;
    private javax.swing.JTextField txtOznaka;
    private javax.swing.JFormattedTextField txtSifra;
    // End of variables declaration//GEN-END:variables
    
    private void popuniMagacine() {
        try {
            ArrayList<Magacin> magacini;
            
            magacini = ClientController.getInstance().getAllMagacin();
            cmbMagacin.removeAllItems();
            
            for(Magacin m: magacini){
                cmbMagacin.addItem(m);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormIzmenaZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    private void popuniRadnike() {
        try {
            ArrayList<Radnik> radnici;
            
            radnici = ClientController.getInstance().getAllRadnik();
            cmbRadnik.removeAllItems();
            
            for(Radnik r: radnici){
                cmbRadnik.addItem(r);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniOrgJed() {
        try {
            ArrayList<OrganizacionaJedinica> jedinice;
            
            jedinice = ClientController.getInstance().getAllOrgJed();
            cmbOrgJed.removeAllItems();
            
            for(OrganizacionaJedinica j: jedinice){
                cmbOrgJed.addItem(j);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosZapisnikaGR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



}
