/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.istorijaStanjaZaliha;

import controller.ClientController;
import domain.IstorijaStanjaZaliha;
import domain.Magacin;
import domain.Proizvod;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.Parent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;



public class FormIzmenaIstorijeStanja extends javax.swing.JDialog {
    
    private IstorijaStanjaZaliha i;
    private String nazivProizvodaStari;
    private Proizvod proStari;
    FormListaIstorijeStanjaZaliha li = (FormListaIstorijeStanjaZaliha) getParent();
    private Proizvod p;

    public FormIzmenaIstorijeStanja(JDialog parent, boolean modal, IstorijaStanjaZaliha i) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Izmena stanja zaliha");
        this.i = i;
        proStari = i.getProizvod();
        nazivProizvodaStari = i.getNazivProizvoda();
        popuniProizvode();
        popuniMagacine();
        cmbProizvod.getModel().setSelectedItem(i.getProizvod());
        //cmbProizvod.setEnabled(false);
        txtDatum.setDate(i.getDatum());
        txtDatum.setEnabled(false);
        txtNaziv.setText(i.getNazivProizvoda());
        txtKolicina.setText(String.valueOf(i.getKolicinaNaStanju()));
        cmbMagacin.getModel().setSelectedItem(i.getMagacin());
        
        
        cmbProizvod.addActionListener((e) -> {
            p = (Proizvod)cmbProizvod.getSelectedItem();
            txtNaziv.setText(p.getNazivProizvoda());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbProizvod = new javax.swing.JComboBox();
        txtDatum = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbMagacin = new javax.swing.JComboBox();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Proizvod:");

        cmbProizvod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Datum:");

        jLabel3.setText("Naziv proizvoda:");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        jLabel4.setText("Kolciina na stanju:");

        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00"))));

        jLabel5.setText("Magacin:");

        cmbMagacin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmeni.setText("Izmeni stanje zaliha");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProizvod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtNaziv)
                            .addComponent(txtKolicina)
                            .addComponent(cmbMagacin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnIzmeni)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            if(txtKolicina.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti kolicinu na stanju!");
                return;
            }
                        
            if(((Proizvod)cmbProizvod.getSelectedItem())!= proStari){
                i.setPok(1);
                i.setNoviProizvod((Proizvod)cmbProizvod.getSelectedItem());
                nazivProizvodaStari = ((Proizvod)cmbProizvod.getSelectedItem()).getNazivProizvoda();
            } else{
                i.setPok(0);
            }
            
            if(txtNaziv.getText().equals(nazivProizvodaStari)){
                i.setNazivProizvoda(null);
            } else
                i.setNazivProizvoda(txtNaziv.getText());

            
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            String datum = dateFormat.format(txtDatum.getDate());
            i.setFormatDate(datum);
            i.setKolicinaNaStanju(Float.parseFloat(txtKolicina.getText()));
            i.setMagacin((Magacin)cmbMagacin.getSelectedItem());
            
            ClientController.getInstance().updateIstorija(i);
            JOptionPane.showMessageDialog(this, "Uspesno izmenjen proizvod.");
            li.refreshTable();
            this.dispose();
            
        }  catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            li.refreshTable();
            this.dispose();
        }
       
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void popuniProizvode() {
        try {
            ArrayList<Proizvod> proizvodi;
            
            proizvodi = ClientController.getInstance().getAllProizvod();
            cmbProizvod.removeAllItems();
      
            for(Proizvod p: proizvodi){
                cmbProizvod.addItem(p);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormUnosIstorijeStanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniMagacine() {
        try {
            ArrayList<Magacin> magacini;
            
            magacini = ClientController.getInstance().getAllMagacin();
            cmbMagacin.removeAllItems();
            
            for(Magacin m: magacini){
                cmbMagacin.addItem(m);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormUnosIstorijeStanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbMagacin;
    private javax.swing.JComboBox cmbProizvod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
