/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.istorijaStanjaZaliha;

import controller.ClientController;
import domain.IstorijaStanjaZaliha;
import domain.Magacin;
import domain.Proizvod;
import java.io.Console;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




public class FormUnosIstorijeStanja extends javax.swing.JDialog {

    private Proizvod p;
    /**
     * Creates new form FormUnosIstorijeStanja
     */
    public FormUnosIstorijeStanja(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos stanja zaliha");
        popuniProizvode();
        popuniMagacine();
        txtNaziv.setText(((Proizvod)cmbProizvod.getSelectedItem()).getNazivProizvoda());
        txtNaziv.setEditable(false);
        
        cmbProizvod.addActionListener((e) -> {
            p = (Proizvod)cmbProizvod.getSelectedItem();
            txtNaziv.setText(p.getNazivProizvoda());
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbProizvod = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbMagacin = new javax.swing.JComboBox();
        btnSacuvaj = new javax.swing.JButton();
        txtDatum = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Proizvod:");

        cmbProizvod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Datum:");

        jLabel3.setText("Naziv proizvoda:");

        jLabel4.setText("Kolicina na stanjiu:");

        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.0"))));

        jLabel5.setText("Magacin:");

        cmbMagacin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSacuvaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj stanje");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKolicina)
                            .addComponent(cmbProizvod, 0, 159, Short.MAX_VALUE)
                            .addComponent(txtNaziv)
                            .addComponent(cmbMagacin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnSacuvaj)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            if(txtDatum.getDate() == null){
                JOptionPane.showMessageDialog(this, "Morate uneti datum!");
                return;
            }
            if(txtKolicina.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti kolicinu na stanju!");
                return;
            }
            
            Proizvod p = (Proizvod)cmbProizvod.getSelectedItem();
            Date datum = txtDatum.getDate();
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            String datum1 = dateFormat.format(datum);
            Float kolicinaNaStanju = Float.parseFloat(txtKolicina.getText());
            Magacin m = (Magacin) cmbMagacin.getSelectedItem();
            
            
            IstorijaStanjaZaliha i = new IstorijaStanjaZaliha(p,datum1, null, kolicinaNaStanju, m);
            ClientController.getInstance().addIstorijaStanja(i);
            FormListaIstorijeStanjaZaliha li = (FormListaIstorijeStanjaZaliha) getParent();
            li.refreshTable();
            JOptionPane.showMessageDialog(this, "Uspesno uneto stanje zaliha.");
            this.dispose();
                    
            } catch (ParseException ex) {
            Logger.getLogger(FormUnosIstorijeStanja.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            //Logger.getLogger(FormUnosIstorijeStanja.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbMagacin;
    private javax.swing.JComboBox cmbProizvod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniProizvode() {
        try {
            ArrayList<Proizvod> proizvodi;
            
            proizvodi = ClientController.getInstance().getAllProizvod();
            cmbProizvod.removeAllItems();
      
            for(Proizvod p: proizvodi){
                cmbProizvod.addItem(p);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormUnosIstorijeStanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniMagacine() {
        try {
            ArrayList<Magacin> magacini;
            
            magacini = ClientController.getInstance().getAllMagacin();
            cmbMagacin.removeAllItems();
            
            for(Magacin m: magacini){
                cmbMagacin.addItem(m);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormUnosIstorijeStanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
