/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.trebovanje;

import controller.ClientController;
import domain.Magacin;
import domain.OrganizacionaJedinica;
import domain.Radnik;
import domain.Trebovanje;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




public class FormUnosTrebovanja extends javax.swing.JDialog {

    /**
     * Creates new form FormUnosTrebovanja
     */
    public FormUnosTrebovanja(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos trebovanja");
        popuniMagacine();
        popuniOrgJed();
        popuniRadnike();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JFormattedTextField();
        txtEvidencioni = new javax.swing.JFormattedTextField();
        txtDatum = new com.toedter.calendar.JDateChooser();
        cmbOrgJedNosilac = new javax.swing.JComboBox();
        cmbOrgJedMesto = new javax.swing.JComboBox();
        cmbRadnikIzradio = new javax.swing.JComboBox();
        cmbRadnikOdobrio = new javax.swing.JComboBox();
        cmbMagacin = new javax.swing.JComboBox();
        btnUnesi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra trebovanja:");

        jLabel2.setText("Evidencioni broj:");

        jLabel3.setText("Datum:");

        jLabel4.setText("Nosilac troska:");

        jLabel5.setText("Mesto troska:");

        jLabel6.setText("Izradio:");

        jLabel7.setText("Odobrio:");

        jLabel8.setText("Magacin:");

        txtSifra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        txtEvidencioni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        txtDatum.setDateFormatString("dd.MM.yyyy.");

        cmbOrgJedNosilac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbOrgJedMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbRadnikIzradio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbRadnikOdobrio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbMagacin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUnesi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnesi.setText("Unesi trebovanje");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEvidencioni, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtSifra)
                            .addComponent(cmbRadnikOdobrio, 0, 186, Short.MAX_VALUE)
                            .addComponent(cmbRadnikIzradio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbOrgJedMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbOrgJedNosilac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMagacin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEvidencioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbOrgJedNosilac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbOrgJedMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbRadnikIzradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbRadnikOdobrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnUnesi)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            if(txtSifra.getText().isEmpty() || txtEvidencioni.getText().isEmpty() || txtDatum.getDate() == null){
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");
                return;
            }
            
            Long sifTrebovanja = Long.parseLong(txtSifra.getText());
            Long evidencioniBroj = Long.parseLong(txtEvidencioni.getText());
            Date datum = txtDatum.getDate();
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            String datum1 = dateFormat.format(datum);
            OrganizacionaJedinica oNosilac = (OrganizacionaJedinica)cmbOrgJedNosilac.getSelectedItem();
            OrganizacionaJedinica oMesto = (OrganizacionaJedinica)cmbOrgJedMesto.getSelectedItem();
            Radnik rIzradio = (Radnik) cmbRadnikIzradio.getSelectedItem();
            Radnik rOdobrio = (Radnik) cmbRadnikOdobrio.getSelectedItem();
            Magacin m = (Magacin)cmbMagacin.getSelectedItem();
            
            Trebovanje t = new Trebovanje(sifTrebovanja, evidencioniBroj, datum1, oNosilac, oMesto, rIzradio, rOdobrio, m);
            
            ClientController.getInstance().addTrebovanje(t);
            FormListaTrebovanja lt = (FormListaTrebovanja) getParent();
            lt.refreshTable();
            JOptionPane.showMessageDialog(this, "Uspesno uneto trebovanje.");
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(FormUnosTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUnesiActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesi;
    private javax.swing.JComboBox cmbMagacin;
    private javax.swing.JComboBox cmbOrgJedMesto;
    private javax.swing.JComboBox cmbOrgJedNosilac;
    private javax.swing.JComboBox cmbRadnikIzradio;
    private javax.swing.JComboBox cmbRadnikOdobrio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JFormattedTextField txtEvidencioni;
    private javax.swing.JFormattedTextField txtSifra;
    // End of variables declaration//GEN-END:variables
    
    private void popuniMagacine() {
        try {
            ArrayList<Magacin> magacini;
            
            magacini = ClientController.getInstance().getAllMagacin();
            cmbMagacin.removeAllItems();
            
            for(Magacin m: magacini){
                cmbMagacin.addItem(m);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    private void popuniOrgJed() {
        try {
            ArrayList<OrganizacionaJedinica> jedinice;
            
            jedinice = ClientController.getInstance().getAllOrgJed();
            cmbOrgJedNosilac.removeAllItems();
            cmbOrgJedMesto.removeAllItems();
            
            for(OrganizacionaJedinica j: jedinice){
                cmbOrgJedNosilac.addItem(j);
                cmbOrgJedMesto.addItem(j);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void popuniRadnike() {
        try {
            ArrayList<Radnik> radnici;
            
            radnici = ClientController.getInstance().getAllRadnik();
            cmbRadnikIzradio.removeAllItems();
            cmbRadnikOdobrio.removeAllItems();
            
            for(Radnik r: radnici){
                cmbRadnikIzradio.addItem(r);
                cmbRadnikOdobrio.addItem(r);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
