/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.trebovanje;

import controller.ClientController;
import domain.Magacin;
import domain.OrganizacionaJedinica;
import domain.Radnik;
import domain.Trebovanje;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




public class FormIzmenaTrebovanja extends javax.swing.JDialog {

    /**
     * Creates new form FormIzmeniTrebovanje
     */
    Trebovanje t;
    public FormIzmenaTrebovanja(JDialog parent, boolean modal, Trebovanje t) {
        super(parent, modal);
        initComponents();
        this.t = t;
        setLocationRelativeTo(null);
        setTitle("Izmana trebovanja");
        popuniMagacine();
        popuniOrgJed();
        popuniRadnike();
        txtSifra.setText(String.valueOf(t.getSifTrebovanja()));
        txtSifra.setEnabled(false);
        txtEvidencioni.setText(String.valueOf(t.getEvidencioniBroj()));
        txtDatum.setDate(t.getDatumDokumenta());
        cmbOrgJedNosilac.getModel().setSelectedItem(t.getOrgJedNosilacTroska());
        cmbOrgJedMesto.getModel().setSelectedItem(t.getOrgJedMestoTroska());
        cmbRadnikIzradio.getModel().setSelectedItem(t.getRadnikIzradio());
        cmbRadnikOdobrio.getModel().setSelectedItem(t.getRadnikOdobrio());
        cmbMagacin.getModel().setSelectedItem(t.getMagacin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEvidencioni = new javax.swing.JFormattedTextField();
        txtDatum = new com.toedter.calendar.JDateChooser();
        cmbOrgJedNosilac = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbOrgJedMesto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbRadnikIzradio = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbRadnikOdobrio = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbMagacin = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtEvidencioni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        txtDatum.setDateFormatString("dd.MM.yyyy.");

        cmbOrgJedNosilac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Evidencioni broj:");

        cmbOrgJedMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Datum:");

        cmbRadnikIzradio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Nosilac troska:");

        cmbRadnikOdobrio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Mesto troska:");

        cmbMagacin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Izradio:");

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmeni.setText("Izmeni trebovanje");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel7.setText("Odobrio:");

        jLabel8.setText("Magacin:");

        jLabel1.setText("Sifra trebovanja:");

        txtSifra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEvidencioni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbRadnikIzradio, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbOrgJedMesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbOrgJedNosilac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbRadnikOdobrio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbMagacin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEvidencioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbOrgJedNosilac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbOrgJedMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbRadnikIzradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbRadnikOdobrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnIzmeni)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            if(txtEvidencioni.getText().isEmpty() || txtDatum.getDate() == null){
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");
                return;
            }
                        
            t.setEvidencioniBroj(Long.parseLong(txtEvidencioni.getText()));
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            String datum = dateFormat.format(txtDatum.getDate());
            t.setFormatDate(datum);
            t.setDatumDokumenta(txtDatum.getDate());
            t.setOrgJedNosilacTroska((OrganizacionaJedinica) cmbOrgJedNosilac.getSelectedItem());
            t.setOrgJedMestoTroska((OrganizacionaJedinica) cmbOrgJedMesto.getSelectedItem());
            t.setRadnikIzradio((Radnik) cmbRadnikIzradio.getSelectedItem());
            t.setRadnikOdobrio((Radnik) cmbRadnikOdobrio.getSelectedItem());
            t.setMagacin((Magacin) cmbMagacin.getSelectedItem());
            
            ClientController.getInstance().updateTrebovanje(t);
            JOptionPane.showMessageDialog(this, "Uspesno izmenjeno trebovanje.");
            FormListaTrebovanja lt = (FormListaTrebovanja) getParent();
            lt.refreshTable();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FormIzmenaTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbMagacin;
    private javax.swing.JComboBox cmbOrgJedMesto;
    private javax.swing.JComboBox cmbOrgJedNosilac;
    private javax.swing.JComboBox cmbRadnikIzradio;
    private javax.swing.JComboBox cmbRadnikOdobrio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JFormattedTextField txtEvidencioni;
    private javax.swing.JFormattedTextField txtSifra;
    // End of variables declaration//GEN-END:variables
    private void popuniMagacine() {
        try {
            ArrayList<Magacin> magacini;
            
            magacini = ClientController.getInstance().getAllMagacin();
            cmbMagacin.removeAllItems();
            
            for(Magacin m: magacini){
                cmbMagacin.addItem(m);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    private void popuniOrgJed() {
        try {
            ArrayList<OrganizacionaJedinica> jedinice;
            
            jedinice = ClientController.getInstance().getAllOrgJed();
            cmbOrgJedNosilac.removeAllItems();
            cmbOrgJedMesto.removeAllItems();
            
            for(OrganizacionaJedinica j: jedinice){
                cmbOrgJedNosilac.addItem(j);
                cmbOrgJedMesto.addItem(j);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void popuniRadnike() {
        try {
            ArrayList<Radnik> radnici;
            
            radnici = ClientController.getInstance().getAllRadnik();
            cmbRadnikIzradio.removeAllItems();
            cmbRadnikOdobrio.removeAllItems();
            
            for(Radnik r: radnici){
                cmbRadnikIzradio.addItem(r);
                cmbRadnikOdobrio.addItem(r);
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormUnosTrebovanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
