/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.proizvod;

import forme.proizvod.FormListaProizvoda;
import controller.ClientController;
import domain.JedinicaMere;
import domain.Proizvod;
import forme.FormMain;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


public class FormIzmenaProizvoda extends javax.swing.JDialog {
    
    private Proizvod p;
    private Float dostupnaKolicinaStara;
    FormListaProizvoda lp = (FormListaProizvoda) getParent();
    
    public FormIzmenaProizvoda(JDialog parent, boolean modal, Proizvod p) {
        super(parent, modal);
        initComponents();
        this.p = p;
        setLocationRelativeTo(null);
        setTitle("Izmena proizvoda");
        dostupnaKolicinaStara = p.getDostupnaKolicina();
        txtSifra.setText(String.valueOf(p.getSifProizvoda()));
        txtSifra.setEnabled(false);
        txtNaziv.setText(p.getNazivProizvoda());
        txtDodatniNaziv.setText(p.getDodatniNaziv());
        txtOznaka.setText(p.getOznaka());
        txtDostupnaKolicina.setText(String.valueOf(p.getDostupnaKolicina()));
        popuniJM();
        cmbJm.getModel().setSelectedItem(p.getJM());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtDodatniNaziv = new javax.swing.JTextField();
        txtOznaka = new javax.swing.JTextField();
        cmbJm = new javax.swing.JComboBox();
        btnIzmeni = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDostupnaKolicina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv proizvoda:");

        jLabel2.setText("Dodatni naziv:");

        jLabel3.setText("Oznaka:");

        jLabel4.setText("Jedinica mere:");

        cmbJm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmeni.setText("Izmeni proizvod");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel5.setText("Sifra proizvoda:");

        jLabel6.setText("Dostupna kolicina:");
        jLabel6.setToolTipText("");

        txtDostupnaKolicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDostupnaKolicinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDostupnaKolicina)
                            .addComponent(cmbJm, 0, 163, Short.MAX_VALUE)
                            .addComponent(txtNaziv)
                            .addComponent(txtSifra)
                            .addComponent(txtDodatniNaziv)
                            .addComponent(txtOznaka)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDodatniNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDostupnaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            if(txtNaziv.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate uneti naziv proizvoda!");
                return;
            }
            p.setSifProizvoda(Long.parseLong(txtSifra.getText()));
            p.setNazivProizvoda(txtNaziv.getText());
            p.setDodatniNaziv(txtDodatniNaziv.getText());
            p.setOznaka(txtOznaka.getText());
            p.setJM((JedinicaMere) cmbJm.getSelectedItem());
            if(Float.parseFloat(txtDostupnaKolicina.getText())!= dostupnaKolicinaStara)
            p.setDostupnaKolicina(Float.parseFloat(txtDostupnaKolicina.getText()));
            else p.setDostupnaKolicina(null);
            
            
            ClientController.getInstance().updateProizvod(p);
            JOptionPane.showMessageDialog(this, "Uspesno izmenjen proizvod.");
            lp.refreshTable();
            this.dispose();
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            lp.refreshTable();
            this.dispose();
            
        }
        
        
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void txtDostupnaKolicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDostupnaKolicinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDostupnaKolicinaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbJm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDodatniNaziv;
    private javax.swing.JTextField txtDostupnaKolicina;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtOznaka;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables

    private void popuniJM() {
       ArrayList<JedinicaMere> jedinice;
        
        try {
            jedinice = ClientController.getInstance().getAllJM();
      
        cmbJm.removeAllItems();
        for(JedinicaMere jm: jedinice){
            cmbJm.addItem(jm);
        }
        } catch (Exception ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
