/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.PoslovniPartnerView;

import controller.ClientController;
import domain.Mesto;
import domain.PoslovniPartnerView;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.shape.Mesh;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


public class FormUnosPoslovnogPartnera extends javax.swing.JDialog {

  
    
    public FormUnosPoslovnogPartnera(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos Poslovnog partnera");
        popuniMesta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JFormattedTextField();
        txtNaziv = new javax.swing.JTextField();
        txtMaticniBroj = new javax.swing.JFormattedTextField();
        txtPIB = new javax.swing.JFormattedTextField();
        txtTekuciRacun = new javax.swing.JFormattedTextField();
        txtAdresa = new javax.swing.JTextField();
        cmbMesto = new javax.swing.JComboBox();
        btnUnesi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra partnera:");

        jLabel2.setText("Naziv partnera:");

        jLabel3.setText("Maticni broj:");

        jLabel4.setText("PIB:");

        jLabel5.setText("Tekuci racun:");

        jLabel6.setText("Adresa:");

        jLabel7.setText("Mesto:");

        txtSifra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txtSifra.setToolTipText("");

        txtMaticniBroj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        txtPIB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        txtTekuciRacun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        cmbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUnesi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnesi.setText("Unesi poslovnog partnera");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSifra)
                    .addComponent(txtNaziv)
                    .addComponent(txtMaticniBroj)
                    .addComponent(txtPIB)
                    .addComponent(txtTekuciRacun)
                    .addComponent(txtAdresa)
                    .addComponent(cmbMesto, 0, 147, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUnesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTekuciRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnUnesi)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            if(txtSifra.getText().isEmpty() || txtNaziv.getText().isEmpty() || txtMaticniBroj.getText().isEmpty() ||  txtPIB.getText().isEmpty() || txtTekuciRacun.getText().isEmpty() || txtAdresa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");
                return;
            }
            Long sifPartnera = Long.parseLong(txtSifra.getText());
            String nazivPartnera = txtNaziv.getText();
            Long maticniBroj = Long.parseLong(txtMaticniBroj.getText());
            Long PIB = Long.parseLong(txtPIB.getText());
            Long tekuciRacun = Long.parseLong(txtTekuciRacun.getText());
            String adresa = txtAdresa.getText();
            Mesto m = (Mesto)cmbMesto.getSelectedItem();
            
            PoslovniPartnerView p = new PoslovniPartnerView(sifPartnera, nazivPartnera, maticniBroj, PIB, adresa, tekuciRacun, m);
            ClientController.getInstance().addPoslovniPartner(p);
            FormListaPoslovnihPartnera lp = (FormListaPoslovnihPartnera) getParent();
            lp.refreshTable();
            JOptionPane.showMessageDialog(this, "Uspesno unet poslovni partner.");
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(FormUnosPoslovnogPartnera.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUnesiActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesi;
    private javax.swing.JComboBox cmbMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JFormattedTextField txtMaticniBroj;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JFormattedTextField txtPIB;
    private javax.swing.JFormattedTextField txtSifra;
    private javax.swing.JFormattedTextField txtTekuciRacun;
    // End of variables declaration//GEN-END:variables

    private void popuniMesta() {
        ArrayList<Mesto> mesta;
        
        try {
            mesta = ClientController.getInstance().getAllMesta();
      
        cmbMesto.removeAllItems();
        for(Mesto m: mesta){
            cmbMesto.addItem(m);
        }
        } catch (Exception ex) {
            Logger.getLogger(FormUnosPoslovnogPartnera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
