/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.PoslovniPartnerView;

import controller.ClientController;
import domain.PoslovniPartnerView;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import models.TableModelPoslovniPartner;
import models.TableModelPoslovniPartnerDetalji;
import models.TableModelPoslovniPartnerView;



public class FormListaPoslovnihPartnera extends javax.swing.JDialog {

    /**
     * Creates new form FormListaPoslovnihPartnera
     */
    public FormListaPoslovnihPartnera(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lista poslovnih partnera");
        TableModelPoslovniPartnerView model = new TableModelPoslovniPartnerView();
        TableModelPoslovniPartner model1 = new TableModelPoslovniPartner();
        TableModelPoslovniPartnerDetalji model2 = new TableModelPoslovniPartnerDetalji();
        Thread th = new Thread();
        th.start();
        tblPoslovniPartnerView.setModel(model);
        tblPoslovniPartner.setModel(model1);
        tblPoslovniPartnerDetalji.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoslovniPartnerView = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPoslovniPartnerDetalji = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPoslovniPartner = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPoslovniPartnerView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPoslovniPartnerView);

        tblPoslovniPartnerDetalji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPoslovniPartnerDetalji);

        jLabel1.setText("Tabela poslovniPartner:");

        jLabel2.setText("Tabela poslovniPartner detalji:");

        tblPoslovniPartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPoslovniPartner);

        btnDodaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDodaj.setText("Unesi partnera");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnObrisi.setText("Obrisi partnera");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmeni.setText("Izmeni partnera");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel3.setText("Pogled poslovniPartner_View:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnDodaj)
                            .addGap(31, 31, 31)
                            .addComponent(btnIzmeni)
                            .addGap(31, 31, 31)
                            .addComponent(btnObrisi))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        new FormUnosPoslovnogPartnera(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
       int row = tblPoslovniPartnerView.getSelectedRow();
       if(row>=0){
           PoslovniPartnerView p = ((TableModelPoslovniPartnerView)tblPoslovniPartnerView.getModel()).getSelectedPoslovniPartner(row);
           new FormIzmenaPoslovnogPartnera(this, rootPaneCheckingEnabled, p).setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(this, "Izaberite poslovnog partnera kog zelite da izmenite!");
       }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblPoslovniPartnerView.getSelectedRow();
        
        if(row>=0){
           PoslovniPartnerView p = ((TableModelPoslovniPartnerView)tblPoslovniPartnerView.getModel()).getSelectedPoslovniPartner(row);
           int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete ovog poslovnog partnera?", "Konfirmacija", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.NO_OPTION){
            return;
            }
            if(result == JOptionPane.YES_OPTION){
               try {
                   ClientController.getInstance().deletePoslovniPartner(p);
                   ((TableModelPoslovniPartnerView)tblPoslovniPartnerView.getModel()).refreshTable();
                   ((TableModelPoslovniPartner)tblPoslovniPartner.getModel()).refreshTable();
                   ((TableModelPoslovniPartnerDetalji)tblPoslovniPartnerDetalji.getModel()).refreshTable();
                   JOptionPane.showMessageDialog(this, "Uspesno obrisan poslovni partner."); 
               } catch (Exception ex) {
                   //Logger.getLogger(FormListaPoslovnihPartnera.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
               }
            }
            
        } else{
           JOptionPane.showMessageDialog(this, "Izaberite poslovnog partnera kog zelite da obrisete!");
        } 
    }//GEN-LAST:event_btnObrisiActionPerformed

    void refreshTable(){
        TableModelPoslovniPartnerView tpv = (TableModelPoslovniPartnerView)tblPoslovniPartnerView.getModel();
        tpv.refreshTable();
        
        TableModelPoslovniPartner tp = (TableModelPoslovniPartner)tblPoslovniPartner.getModel();
        tp.refreshTable();
        
        TableModelPoslovniPartnerDetalji tpd = (TableModelPoslovniPartnerDetalji)tblPoslovniPartnerDetalji.getModel();
        tpd.refreshTable();
    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPoslovniPartner;
    private javax.swing.JTable tblPoslovniPartnerDetalji;
    private javax.swing.JTable tblPoslovniPartnerView;
    // End of variables declaration//GEN-END:variables
}
