/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.pakovanje;

import controller.ClientController;
import domain.Pakovanje;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import models.TableModelPakovanje;




public class FormListaPakovanja extends javax.swing.JDialog {

    /**
     * Creates new form FormListaPakovanja
     */
    public FormListaPakovanja(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lista pakovanja");
        TableModelPakovanje model = new TableModelPakovanje();
        Thread th = new Thread();
        th.start();
        tblPakovanja.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPakovanja = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnUnesi = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPakovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPakovanja);

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmeni.setText("Izmeni pakovanje");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnUnesi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnesi.setText("Unesi pakovanje");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnObrisi.setText("Obrisi pakovanje");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnesi)
                        .addGap(45, 45, 45)
                        .addComponent(btnIzmeni)
                        .addGap(35, 35, 35)
                        .addComponent(btnObrisi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        new FormUnosPakovanja(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int row = tblPakovanja.getSelectedRow();
        if(row>=0){
            Pakovanje p = ((TableModelPakovanje)tblPakovanja.getModel()).getSelectedPakovanje(row);
           new FormIzmenaPakovanja(this, rootPaneCheckingEnabled, p).setVisible(true);
        }
        else{
           JOptionPane.showMessageDialog(this, "Izaberite pakovanje koje zelite da izmenite!");
       }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblPakovanja.getSelectedRow();
        
        if(row>=0){
           Pakovanje p = ((TableModelPakovanje)tblPakovanja.getModel()).getSelectedPakovanje(row);
           int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete ovo pakovanje?", "Konfirmacija", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.NO_OPTION){
            return;
            }
            if(result == JOptionPane.YES_OPTION){
               try {
                   ClientController.getInstance().deletePakovanje(p);
                   ((TableModelPakovanje)tblPakovanja.getModel()).refreshTable();
                   JOptionPane.showMessageDialog(this, "Uspesno obrisano pakovanje."); 
               } catch (Exception ex) {
                   Logger.getLogger(FormListaPakovanja.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
            
        } else{
           JOptionPane.showMessageDialog(this, "Izaberite pakovanje koje zelite da obrisete!");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPakovanja;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
        TableModelPakovanje tp = (TableModelPakovanje)tblPakovanja.getModel();
        tp.refreshTable();
    }
}
