/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.stavkaZapisnikaOPrijemuMaterijala;

import controller.ClientController;
import domain.StavkaZapisnikaOPrijemuMaterijala;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableStringConverter;
import models.TableModelIstorija;
import models.TableModelStavkaZOPM;




public class FormListaStavkiZOPM extends javax.swing.JDialog {

    /**
     * Creates new form FormListaStavkiZOPM
     */
    public FormListaStavkiZOPM(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lista zapisnika o prijemu materijala");
        TableModelStavkaZOPM model = new TableModelStavkaZOPM();
        Thread th = new Thread();
        th.start();
        tblStavki.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavki = new javax.swing.JTable();
        btnBrisanje = new javax.swing.JButton();
        btnUnos = new javax.swing.JButton();
        btnIzmena = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblStavki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavki);

        btnBrisanje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBrisanje.setText("Obrisi stavku");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        btnUnos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnos.setText("Unesi stavku");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        btnIzmena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzmena.setText("Izmeni stavku");
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretraga (sifZOPM):");

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)
                            .addComponent(btnIzmena, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnos)
                    .addComponent(btnIzmena)
                    .addComponent(btnBrisanje))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
        new FormUnosStavkeZOPM(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
         String param = txtPretraga.getText();
        ((TableModelStavkaZOPM)tblStavki.getModel()).setParametar(param);
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed
       int row = tblStavki.getSelectedRow();
       if(row>=0){
           StavkaZapisnikaOPrijemuMaterijala s = ((TableModelStavkaZOPM)tblStavki.getModel()).getSelectedstavka(row);
            new FormIzmenaStavkeZOPM(this, rootPaneCheckingEnabled, s).setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(this, "Izaberite stavku zapisnika koje zelite da izmenite!");
       }
    }//GEN-LAST:event_btnIzmenaActionPerformed

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        int row = tblStavki.getSelectedRow();
        
        if(row>=0){
           StavkaZapisnikaOPrijemuMaterijala s = ((TableModelStavkaZOPM)tblStavki.getModel()).getSelectedstavka(row);
           int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete ovu stavku?", "Konfirmacija", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.NO_OPTION){
                return;
            }
            if(result == JOptionPane.YES_OPTION){
               try {
                   ClientController.getInstance().deleteStavkaZOPM(s);
                   ((TableModelStavkaZOPM)tblStavki.getModel()).refreshTable();
                   JOptionPane.showMessageDialog(this, "Uspesno obrisana stavka."); 
               } catch (Exception ex) {
                   Logger.getLogger(FormListaStavkiZOPM.class.getName()).log(Level.SEVERE, null, ex);
               }
            } 
        } else{
           JOptionPane.showMessageDialog(this, "Izaberite stavku koji zelite da obrisete!");
        } 
    }//GEN-LAST:event_btnBrisanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void refreshTable(){
        TableModelStavkaZOPM ts = (TableModelStavkaZOPM)tblStavki.getModel();
        ts.refreshTable();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnIzmena;
    private javax.swing.JButton btnUnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavki;
    private javax.swing.JFormattedTextField txtPretraga;
    // End of variables declaration//GEN-END:variables
}
